name: ai-project

networks:
  ai-network:
    name: ai-network

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    networks:
      - ai-network
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ../.volumes/ollama:/root/.ollama

  open-web-ui:
    container_name: open-web-ui
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - ai-network
    ports:
      - 8500:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ../.volumes/open-web-ui:/app/backend/data

  mcp-database-server:
    container_name: mcp-database-server
    build:
      context: ../mcp-database-server
      dockerfile: Dockerfile.mcpo
    networks:
      - ai-network
    ports:
      - 3000:3000
    environment:
      - API_AUTH_TOKEN=${API_AUTH_TOKEN}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - DATABASE_CONNECTION_TIMEOUT=${DATABASE_CONNECTION_TIMEOUT}